apiVersion: v1
kind: Service
metadata:
  name: my-udagram-reverseproxy
  labels:
    run: my-udagram-reverseproxy
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    service: my-udagram-reverseproxy
